namespace $.$$ {

	const bases = [ 'slate', 'stone', 'zinc', 'gray' ] as const
	const themes = [ 'sky', 'rose', 'violet', 'emerald', 'amber' ] as const
	const fonts = [ 'inter', 'manrope', 'dm-sans', 'eb-garamond' ] as const
	const radii = [ 'none', 'small', 'medium', 'large' ] as const
	const lights_list = [ 'dark', 'light' ] as const

	const titleize = ( s: string ) =>
		s.split( '-' ).map( w => w[ 0 ].toUpperCase() + w.slice( 1 ) ).join( ' ' )

	const cycle = < T extends readonly string[] >( list: T, current: T[ number ] ): T[ number ] => {
		const i = list.indexOf( current )
		return list[ ( i + 1 ) % list.length ]
	}

	const ZIP_FILES = [
		'theme.css',
		'builderui.ts',
		'div/div.view.tree',
		'div/div.view.css.ts',
		'button/button.view.tree',
		'button/button.view.css.ts',
		'card/card.view.tree',
		'card/card.view.css.ts',
		'field/field.view.tree',
		'field/field.view.css.ts',
		'badge/badge.view.tree',
		'badge/badge.view.css.ts',
		'alert/alert.view.tree',
		'alert/alert.view.css.ts',
		'menu/menu.view.tree',
		'menu/menu.view.css.ts',
		'chart/chart.view.tree',
		'chart/chart.view.css.ts',
	]

	const README = `# BuilderUI kit

Drop this whole \`builderui/\` folder into your bog/ namespace, then wrap your app's root view in $bog_builderui_div and set the preset attributes on it (or on <body>):

  <body
    bog_builderui_lights="dark"
    bog_builderui_base="slate"
    bog_builderui_theme="sky"
    bog_builderui_radius="medium"
    bog_builderui_font_body="inter"
    bog_builderui_font_head="inter"
  >

Components: $bog_builderui_div, $bog_builderui_button, $bog_builderui_card, $bog_builderui_field, $bog_builderui_badge, $bog_builderui_alert, $bog_builderui_menu, $bog_builderui_chart.

Generated by BuilderUI Studio.
`

	export class $bog_builderui_studio extends $.$bog_builderui_studio {

		base_cycle() { this.base( cycle( bases, this.base() as typeof bases[ number ] ) ) }
		theme_cycle() { this.theme( cycle( themes, this.theme() as typeof themes[ number ] ) ) }
		font_head_cycle() { this.font_head( cycle( fonts, this.font_head() as typeof fonts[ number ] ) ) }
		font_body_cycle() { this.font_body( cycle( fonts, this.font_body() as typeof fonts[ number ] ) ) }
		radius_cycle() { this.radius( cycle( radii, this.radius() as typeof radii[ number ] ) ) }
		lights_cycle() { this.lights( cycle( lights_list, this.lights() as typeof lights_list[ number ] ) ) }

		base_label() { return titleize( this.base() ) }
		theme_label() { return titleize( this.theme() ) }
		font_head_label() { return titleize( this.font_head() ) }
		font_body_label() { return titleize( this.font_body() ) }
		radius_label() { return titleize( this.radius() ) }
		lights_label() { return titleize( this.lights() ) }

		chart_series() {
			return [ 24, 38, 32, 51, 44, 60, 55 ]
		}

		chart_color() {
			return 'var(--bog_builderui_control)'
		}

		get_code() {
			$mol_wire_async( this ).download_zip()
		}

		async download_zip() {
			const JSZip = ( globalThis as any ).JSZip
			if( !JSZip ) throw new Error( 'JSZip not loaded' )
			const zip = new JSZip()
			const root = zip.folder( 'builderui' )!
			root.file( 'README.md', README )
			for( const path of ZIP_FILES ) {
				const res = await fetch( '/bog/builderui/' + path )
				const text = await res.text()
				root.file( path, text )
			}
			const blob = await zip.generateAsync( { type: 'blob' } )
			const url = URL.createObjectURL( blob )
			const a = document.createElement( 'a' )
			a.href = url
			a.download = 'builderui.zip'
			document.body.appendChild( a )
			a.click()
			a.remove()
			URL.revokeObjectURL( url )
		}

	}
}
