namespace $.$$ {

	const bases = [ 'slate', 'stone', 'zinc', 'gray' ] as const
	const themes = [ 'sky', 'rose', 'violet', 'emerald', 'amber' ] as const
	const charts = [ 'blue', 'green', 'red', 'yellow', 'purple' ] as const
	const fonts = [ 'inter', 'manrope', 'dm-sans', 'eb-garamond' ] as const
	const radii = [ 'none', 'small', 'medium', 'large' ] as const
	const lights_list = [ 'dark', 'light' ] as const

	type Style = {
		name: string
		base: typeof bases[ number ]
		theme: typeof themes[ number ]
		chart: typeof charts[ number ]
		font: typeof fonts[ number ]
		radius: typeof radii[ number ]
	}
	const styles: Style[] = [
		{ name: 'Default', base: 'slate', theme: 'sky', chart: 'blue', font: 'inter', radius: 'medium' },
		{ name: 'Maia', base: 'stone', theme: 'amber', chart: 'yellow', font: 'eb-garamond', radius: 'large' },
		{ name: 'Mira', base: 'zinc', theme: 'violet', chart: 'purple', font: 'dm-sans', radius: 'small' },
		{ name: 'Sage', base: 'gray', theme: 'emerald', chart: 'green', font: 'manrope', radius: 'medium' },
	]

	const titleize = ( s: string ) =>
		s.split( '-' ).map( w => w[ 0 ].toUpperCase() + w.slice( 1 ) ).join( ' ' )

	const cycle = < T extends readonly string[] >( list: T, current: T[ number ] ): T[ number ] => {
		const i = list.indexOf( current )
		return list[ ( i + 1 ) % list.length ]
	}

	const ZIP_FILES = [
		'theme.css',
		'builderui.ts',
		'div/div.view.tree',
		'div/div.view.css.ts',
		'button/button.view.tree',
		'button/button.view.css.ts',
		'card/card.view.tree',
		'card/card.view.css.ts',
		'field/field.view.tree',
		'field/field.view.css.ts',
		'badge/badge.view.tree',
		'badge/badge.view.css.ts',
		'alert/alert.view.tree',
		'alert/alert.view.css.ts',
		'menu/menu.view.tree',
		'menu/menu.view.css.ts',
		'select/select.view.tree',
		'select/select.view.css.ts',
		'tabs/tabs.view.tree',
		'tabs/tabs.view.css.ts',
		'chart/chart.view.tree',
		'chart/chart.view.css.ts',
	]

	const README = `# BuilderUI kit

Drop this whole \`builderui/\` folder into your bog/ namespace, then wrap your app's root view in $bog_builderui_div and set the preset attributes on it (or on <body>):

  <body
    bog_builderui_lights="dark"
    bog_builderui_base="slate"
    bog_builderui_theme="sky"
    bog_builderui_chart="blue"
    bog_builderui_radius="medium"
    bog_builderui_font_body="inter"
    bog_builderui_font_head="inter"
  >

Components: $bog_builderui_div, $bog_builderui_button, $bog_builderui_card, $bog_builderui_field, $bog_builderui_badge, $bog_builderui_alert, $bog_builderui_menu, $bog_builderui_select, $bog_builderui_tabs, $bog_builderui_chart.

Generated by BuilderUI Studio.
`

	export class $bog_builderui_studio extends $.$bog_builderui_studio {

		shuffle() {
			const pick = < T extends readonly string[] >( list: T ) => list[ Math.floor( Math.random() * list.length ) ]
			this.base( pick( bases ) )
			this.theme( pick( themes ) )
			this.chart( pick( charts ) )
			this.font_body( pick( fonts ) )
			this.font_head( pick( fonts ) )
			this.radius( pick( radii ) )
		}

		base_cycle() { this.base( cycle( bases, this.base() as typeof bases[ number ] ) ) }
		theme_cycle() { this.theme( cycle( themes, this.theme() as typeof themes[ number ] ) ) }
		chart_cycle() { this.chart( cycle( charts, this.chart() as typeof charts[ number ] ) ) }
		font_head_cycle() { this.font_head( cycle( fonts, this.font_head() as typeof fonts[ number ] ) ) }
		font_body_cycle() { this.font_body( cycle( fonts, this.font_body() as typeof fonts[ number ] ) ) }
		radius_cycle() { this.radius( cycle( radii, this.radius() as typeof radii[ number ] ) ) }
		lights_cycle() { this.lights( cycle( lights_list, this.lights() as typeof lights_list[ number ] ) ) }

		base_label() { return titleize( this.base() ) }
		theme_label() { return titleize( this.theme() ) }
		chart_label() { return titleize( this.chart() ) }
		font_head_label() { return titleize( this.font_head() ) }
		font_body_label() { return titleize( this.font_body() ) }
		radius_label() { return titleize( this.radius() ) }
		lights_label() { return titleize( this.lights() ) }

		style_index() {
			return styles.findIndex( s =>
				s.base === this.base() &&
				s.theme === this.theme() &&
				s.chart === this.chart() &&
				s.font === this.font_body() &&
				s.radius === this.radius()
			)
		}
		style_label() {
			const i = this.style_index()
			return i < 0 ? 'Custom' : styles[ i ].name
		}
		style_cycle() {
			const i = this.style_index()
			const next = styles[ ( ( i < 0 ? -1 : i ) + 1 ) % styles.length ]
			this.base( next.base )
			this.theme( next.theme )
			this.chart( next.chart )
			this.font_body( next.font )
			this.font_head( next.font )
			this.radius( next.radius )
		}

		chart_visits() { return [ 24, 38, 32, 51, 44, 60, 55 ] }
		chart_signups() { return [ 14, 22, 18, 30, 26, 36, 32 ] }
		chart_logins() { return [ 9, 14, 12, 19, 18, 24, 22 ] }
		chart_labels() { return [ 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun' ] }
		chart_color_visits() { return 'var(--bog_builderui_chart)' }
		chart_color_signups() { return 'var(--bog_builderui_special)' }
		chart_color_logins() { return 'var(--bog_builderui_current)' }

		get_code() {
			$mol_wire_async( this ).download_zip()
		}

		async download_zip() {
			const JSZip = ( globalThis as any ).JSZip
			if( !JSZip ) throw new Error( 'JSZip not loaded' )
			const zip = new JSZip()
			const root = zip.folder( 'builderui' )!
			root.file( 'README.md', README )
			for( const path of ZIP_FILES ) {
				const res = await fetch( '/bog/builderui/' + path )
				const text = await res.text()
				root.file( path, text )
			}
			const blob = await zip.generateAsync( { type: 'blob' } )
			const url = URL.createObjectURL( blob )
			const a = document.createElement( 'a' )
			a.href = url
			a.download = 'builderui.zip'
			document.body.appendChild( a )
			a.click()
			a.remove()
			URL.revokeObjectURL( url )
		}

	}
}
